### ISSUE TITLE
Error when executing with binder 

### ISSUE THREAD

**Issue by amanmdesai** [simonthor/PyHEP2022#1]
Hi @simonthor, Thanks for the very nice talk at PyHEP22. 
I was trying to follow the analysis over binder today (using binder link given in readme). I encountered the following error.

**Error Message**
```code
ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
```
Any idea of how I can fix/run this over binder? 

Thanks

**Comment by simonthor** [comment]
There was a problem with a dependency missing. It should have been fixed now. Thanks for pointing this out!

**Comment by amanmdesai** [comment]
Thanks @simonthor I am able to execute the code now!
