### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [simonthor/PyHEP2022#2]
Hello @simonthor, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by simonthor** [comment]
Thank you for notifying about this! Is [this](https://github.com/simonthor/PyHEP2022/releases/tag/PyHEP-2022) enough, or should I do something more?

**Comment by eduardo-rodrigues** [comment]
That's all I need. Thanks.
